version: "2"
services:
  server:
    image: test_crud
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5050:5432"
